export {default as Modal} from './modal.astro'
export {default as List} from './list.astro'
export {default as Slider} from './slider/slider.astro'
export {default as Chapter} from './chapter.astro'
export {MoreInfo} from './moreInfo.tsx'
